// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Account", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("userId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("account");
                });

            modelBuilder.Entity("Domain.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("userId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("id");

                    b.HasIndex("userId", "name", "type")
                        .IsUnique();

                    b.ToTable("category");
                });

            modelBuilder.Entity("Domain.Models.Goal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<decimal>("currentAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("currentAmount");

                    b.Property<DateOnly?>("deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("totalAmount");

                    b.Property<int>("userId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("goal");
                });

            modelBuilder.Entity("Domain.Models.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("accountId")
                        .HasColumnType("integer")
                        .HasColumnName("accountId");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<int>("categoryId")
                        .HasColumnType("integer")
                        .HasColumnName("categoryId");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("transactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transactionDate");

                    b.Property<int>("type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("id");

                    b.HasIndex("accountId");

                    b.HasIndex("categoryId");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("Domain.Models.TransactionGoal", b =>
                {
                    b.Property<int>("transactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transactionId")
                        .HasColumnOrder(0);

                    b.Property<int>("goalId")
                        .HasColumnType("integer")
                        .HasColumnName("goalId")
                        .HasColumnOrder(1);

                    b.Property<decimal>("contributedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("contributedAmount");

                    b.HasKey("transactionId", "goalId");

                    b.HasIndex("goalId");

                    b.ToTable("transaction_goal");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("creationDate")
                        .HasColumnType("date")
                        .HasColumnName("creationDate");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Domain.Models.Account", b =>
                {
                    b.HasOne("Domain.Models.User", "user")
                        .WithMany("accounts")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.Models.Category", b =>
                {
                    b.HasOne("Domain.Models.User", "user")
                        .WithMany("categories")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.Models.Goal", b =>
                {
                    b.HasOne("Domain.Models.User", "user")
                        .WithMany("goals")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Domain.Models.Transaction", b =>
                {
                    b.HasOne("Domain.Models.Account", "account")
                        .WithMany("transactions")
                        .HasForeignKey("accountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Category", "category")
                        .WithMany("transactions")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("account");

                    b.Navigation("category");
                });

            modelBuilder.Entity("Domain.Models.TransactionGoal", b =>
                {
                    b.HasOne("Domain.Models.Goal", "goal")
                        .WithMany("transactionGoals")
                        .HasForeignKey("goalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Transaction", "transaction")
                        .WithMany("transactionGoals")
                        .HasForeignKey("transactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("goal");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("Domain.Models.Account", b =>
                {
                    b.Navigation("transactions");
                });

            modelBuilder.Entity("Domain.Models.Category", b =>
                {
                    b.Navigation("transactions");
                });

            modelBuilder.Entity("Domain.Models.Goal", b =>
                {
                    b.Navigation("transactionGoals");
                });

            modelBuilder.Entity("Domain.Models.Transaction", b =>
                {
                    b.Navigation("transactionGoals");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("accounts");

                    b.Navigation("categories");

                    b.Navigation("goals");
                });
#pragma warning restore 612, 618
        }
    }
}
